# This file was generated by GoReleaser. DO NOT EDIT.
cask "terrable" do
  name "terrable"
  desc ""
  homepage ""
  version "0.12.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terrable"

  on_macos do
    on_intel do
      url "https://github.com/terrable-dev/terrable/releases/download/v#{version}/terrable_Darwin_x86_64.tar.gz"
      sha256 "4bdebdd83741df3eb134ae10bdb076f3c0c86233cf734a4ea0448540bde53099"
    end
    on_arm do
      url "https://github.com/terrable-dev/terrable/releases/download/v#{version}/terrable_Darwin_arm64.tar.gz"
      sha256 "ceb219477f57a7175cb76da2ae1235d58e3931c6122310d0dcf1bbebf180ac34"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/terrable-dev/terrable/releases/download/v#{version}/terrable_Linux_x86_64.tar.gz"
      sha256 "7e3ef3952afdb7d3ab7eb09a7935287a942aa52951ff71e401bb6da9fa99398f"
    end
    on_arm do
      url "https://github.com/terrable-dev/terrable/releases/download/v#{version}/terrable_Linux_arm64.tar.gz"
      sha256 "6ea9b700a618975c7f4ce59a58ad0e9a975606bab63cfef82d138ae65b9a22dd"
    end
  end

  # No zap stanza required
end
