# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terrable < Formula
  desc ""
  homepage ""
  version "0.6.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/terrable-dev/terrable/releases/download/v0.6.2/terrable_Darwin_x86_64.tar.gz"
      sha256 "b08f37d5660de8f202423a95d104cd65b8f2e9dc3080d4a93fe4cb24e92eb0e4"

      def install
        bin.install "terrable"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/terrable-dev/terrable/releases/download/v0.6.2/terrable_Darwin_arm64.tar.gz"
      sha256 "aeee24ef1296f8a61fa67373ed64df6dcfd10e9d70ebcac4fa941cd098fb3e10"

      def install
        bin.install "terrable"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/terrable-dev/terrable/releases/download/v0.6.2/terrable_Linux_x86_64.tar.gz"
        sha256 "879e25d72113d7e12a3aa40742aba745f78029b64b77919fc5a19d03ae48d39e"

        def install
          bin.install "terrable"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/terrable-dev/terrable/releases/download/v0.6.2/terrable_Linux_arm64.tar.gz"
        sha256 "dc9695edfb75dbe9ebae6874cd8cd60696abbbeba08529f2dc33bfcca62689da"

        def install
          bin.install "terrable"
        end
      end
    end
  end
end
