# This file was generated by GoReleaser. DO NOT EDIT.
cask "terrable" do
  name "terrable"
  desc ""
  homepage ""
  version "0.12.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terrable"

  on_macos do
    on_intel do
      url "https://github.com/terrable-dev/terrable/releases/download/v#{version}/terrable_Darwin_x86_64.tar.gz"
      sha256 "7bcaf9fbf3a485c35361dfc0df966987757ecd83a882282a1ed243cb444508cf"
    end
    on_arm do
      url "https://github.com/terrable-dev/terrable/releases/download/v#{version}/terrable_Darwin_arm64.tar.gz"
      sha256 "74fec37149417119d9fd562af76b6ab532f34a0763723336874f441c17429960"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/terrable-dev/terrable/releases/download/v#{version}/terrable_Linux_x86_64.tar.gz"
      sha256 "5a16429931cb2f21120adc6d428a147a07c9a7fbe21b2e06dbb8a3c3adbe9780"
    end
    on_arm do
      url "https://github.com/terrable-dev/terrable/releases/download/v#{version}/terrable_Linux_arm64.tar.gz"
      sha256 "6309b7c361a6eb03f15eb2169deb5557609a6f1100884c72818a02e345436cb1"
    end
  end

  # No zap stanza required
end
